######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 9 20:22:56 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ciphers.h huffman.h mainwindow.h rsa.h rsa_files.h
FORMS += mainwindow.ui
SOURCES += ciphers.cpp main.cpp mainwindow.cpp rsa.cpp rsa_files.cpp
RESOURCES += resources.qrc
TRANSLATIONS += khrypto_pl.ts
